name: Feedback
description: Use this form to submit feedback, feature ideas, or bug reports for HelloCelo V2.
title: "Feedback: ${{ inputs.category }}"
labels: ["feedback"]
body:
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Choose the category that best fits your feedback
      options:
        - Functionality
        - UX/UI
        - New Feature
        - Tokenomics & Rewards
        - Bug
        - Other
  - type: input
    id: summary
    attributes:
      label: Short summary
      description: One-line summary of your feedback or issue
      placeholder: "e.g. Staking UI is not intuitive"
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide detailed description, expected vs actual behavior, or suggestions
      placeholder: "Describe the issue or suggestion..."
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: If reporting a bug, list steps to reproduce it (optional)
      placeholder: "1) Open app, 2) ..."
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser, wallet, network, OS (optional)
      placeholder: "e.g. Chrome, Valora, Alfajores"
  - type: markdown
    attributes:
      value: "After submitting, you can add screenshots or attach files in the issue comments."
